# Generated by Django 4.0.4 on 2022-05-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
