# Generated by Django 4.0.4 on 2022-05-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='incomeTaxHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_amount', models.FloatField()),
                ('deductions_amount', models.FloatField()),
                ('tax_amount', models.FloatField()),
                ('calculation_date', models.DateField()),
            ],
        ),
    ]
